name: Generate 3D Contribution Graph

on:
  schedule:
    - cron: "0 2 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    name: Generate 3D Contribution Graph
    steps:
      - uses: actions/checkout@v4

      - uses: yoshi389111/github-profile-3d-contrib@0.7.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          username: piush365
          max_repos: 10
          type: svg
          theme: dracula

      - name: Move graph to profile directory
        run: mkdir -p profile && mv profile-3d-contrib.svg profile/profile-3d-contrib.svg

      - name: Commit and push
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: update 3D contribution graph"
          branch: main
