name: Generate Stats Images

on:
  schedule:
    - cron: "0 0 * * *" # Runs automatically every day at midnight
  workflow_dispatch: # Allows you to trigger the script manually

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate GitHub Stats
        uses: stats-organization/github-readme-stats-action@v2
        with:
          card: stats
          options: username=piush365&show_icons=true&theme=radical&hide_border=true&bg_color=0D1117
          token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Generate Top Languages
        uses: stats-organization/github-readme-stats-action@v2
        with:
          card: top-langs
          options: username=piush365&layout=compact&theme=radical&hide_border=true&bg_color=0D1117
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: update GitHub stats cards"
